<?xml version="1.0"?>

<robot>

  <macro name="dummy-inertial">
    <inertial>
      <mass value="0.0001" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </macro>
  
  <macro name="dummy-link" params="name">
    <link name="${name}">
      <dummy-inertial />
    </link>
  </macro>

  <macro name="laser-link" params="name">
    <link name="${name}">
      <dummy-inertial />
      <visual>
        <material name="Black" />
        <geometry>
          <cylinder radius="0.0265" length="0.08" />
        </geometry>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="0.0265" length="0.08" />
        </geometry>
      </collision>
    </link>
  </macro>

  <include filename="$(find parsec_description)/urdf/colors.xacro" />
  <include filename="$(find parsec_description)/urdf/calibration.xacro" />
  <include filename="$(find parsec_description)/urdf/gazebo.xacro" />

  <dummy-link name="base_footprint" />
  
  <link name="base_link">
    <inertial>
      <!-- We are just approximating the inertia matrix here by using
           the formula for a solid cylinder. The weight is just
           guessed. -->
      <mass value="15.0" />
      <inertia ixx="0.0033" ixy="0" ixz="0" iyy="0.0033" iyz="0" izz="0.0315315" />
    </inertial>
    <visual>
      <material name="Black" />
      <geometry>
        <cylinder radius="${robot_radius}" length="0.01" />
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${robot_radius}" length="0.01" />
      </geometry>
    </collision>
  </link>

  <link name="left_wheel_link" >
    <inertial>
      <!-- Guessing the inertia matrix by approximating a wheel's
           weight with 0.5kg and using the formula for a solid
           cylinder -->
      <mass value="1.45" />
      <inertia ixx="0.00013716" ixy="0" ixz="0" iyy="0.00013716" iyz="0" izz="0.002032" />
    </inertial>
    <visual>
      <material name="Black" />      
      <geometry>
        <cylinder radius="${wheel_radius}" length="0.032" />
        <color rgba="0 0 0 1" />
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="0.032" />
      </geometry>
    </collision>
  </link>

  <link name="right_wheel_link" >
    <inertial>
      <!-- Guessing the inertia matrix by approximating a wheel's
           weight with 0.5kg and using the formula for a solid
           cylinder -->
      <mass value="1.45" />
      <inertia ixx="0.00013716" ixy="0" ixz="0" iyy="0.00013716" iyz="0" izz="0.002032" />      
    </inertial>
    <visual>
      <material name="Black" />      
      <geometry>
        <cylinder radius="${wheel_radius}" length="0.032" />
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="0.032" />
      </geometry>
    </collision>
  </link>
  
  <link name="front_caster_link">
    <dummy-inertial />
    <visual>
      <origin xyz="0 0 -0.0381" />
      <material name="Black" />      
      <geometry>
        <box size="0.03 0.03 ${wheel_radius}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 -0.0381" />      
      <geometry>
        <box size="0.03 0.03 ${wheel_radius}" />
      </geometry>
    </collision>    
  </link>
  
  <link name="rear_caster_link">
    <dummy-inertial />    
    <visual>
      <origin xyz="0 0 -0.0381" />
      <material name="Black" />      
      <geometry>
        <box size="0.03 0.03 ${wheel_radius}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 -0.0381" />
      <geometry>
        <box size="0.03 0.03 ${wheel_radius}" />
      </geometry>
    </collision>
  </link>
  
  <link name="mast_link">
    <!-- A heavy mast makes the model very unstable in gazebo. -->
    <!-- <mass value="1.5" /> -->
    <!-- <inertia ixx="0.3403626" ixy="0" ixz="0" iyy="0.3405125" iyz="0" izz="0.00025" /> -->
    <dummy-inertial />
    <!-- The origin of the mast is at the origin of the base
         link. That means that we need to move the visual and
         collision elements up by heigt / 2.-->
    <visual>
      <material name="Grey" />
      <origin xyz="0 0 ${mast_height / 2}" />
      <geometry>
        <box size="0.04 0.02 ${mast_height}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0.825" />
      <geometry>
        <box size="0.04 0.02 ${mast_height}" />
      </geometry>
    </collision>
  </link>

  <laser-link name="base_laser" />

  <laser-link name="tilt_laser" />

  <laser-link name="fixed_angle_laser" />
  
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint" />
    <child link="base_link" />
    <origin xyz="0 0 0.0762" rpy="0 0 0" />
  </joint>
            
  <!-- <joint name="left_wheel_joint" type="continuous"> -->
  <joint name="left_wheel_joint" type="fixed">
    <parent link="base_link" />
    <child link="left_wheel_link" />
    <origin xyz="0 0.195 0" rpy="1.5707963268 0 0" />
    <axis xyz="0 0 1" />
  </joint>

  <!-- <joint name="right_wheel_joint" type="continuous"> -->
  <joint name="right_wheel_joint" type="fixed">
    <parent link="base_link" />
    <child link="right_wheel_link" />
    <origin xyz="0 -0.195 0" rpy="1.5707963268 0 0" />
    <axis xyz="0 0 1" />
  </joint>

  <joint name="front_caster_joint" type="fixed">
    <parent link="base_link" />
    <child link="front_caster_link" />
    <origin xyz="0.15 0 0" />
  </joint>

  <joint name="rear_caster_joint" type="fixed">
    <parent link="base_link" />
    <child link="rear_caster_link" />
    <origin xyz="-0.15 0 0" />
  </joint>

  <joint name="mast_joint" type="fixed">
    <parent link="base_link" />
    <child link="mast_link" />
    <origin xyz="0 0 0" />
  </joint>

  <joint name="base_laser_joint" type="fixed">
    <parent link="mast_link" />
    <child link="base_laser" />
    <insert_block name="base_laser_origin" />
  </joint>

  <joint name="tilt_laser_joint" type="revolute">
    <parent link="mast_link" />
    <child link="tilt_laser" />
    <insert_block name="tilting_laser_origin" />    
    <axis xyz="0 1 0" />
    <!-- Using dummy effort and velocity values here. They are not
         used on the parsec -->
    <limit lower="-1.5707963268" upper="1.5707963268"
           effort="1.0" velocity="10.0" />
  </joint>

  <joint name="fixed_angle_laser_joint" type="fixed">
    <parent link="mast_link" />
    <child link="fixed_angle_laser" />
    <insert_block name="fixed_angle_laser_origin" />    
  </joint>
</robot>
