obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.22
inflation_radius: 0.30
observation_sources: "base_laser tilt_laser ground_object_cloud cliff_cloud"
base_laser:
  data_type: PointCloud
  topic: /base_cloud
  marking: true
  clearing: true
  observation_persistance: 0.5
tilt_laser:
  data_type: LaserScan
  topic: /tilt_scan
  marking: false
  clearing: true
ground_object_cloud:
  topic: /floor_filter/filtered_cloud_points1
  data_type: PointCloud
  expected_update_rate: 5.0
  # observation_persistance is necessary when clearing is
  # enabled. Otherwise, subsequent scans clear lower voxels too early.
  observation_persistence: 5.0
  marking: true
  # Clearing is necessary to set voxels to free if the laser scanner
  # clearly could see through it. This is particularly important for
  # points on the floor will not be cleared out by the tilt_laser
  # observation source since the floor appears in the raw scan.
  clearing: true
cliff_cloud:
  topic: /floor_filter/cliff_cloud_points1
  data_type: PointCloud
  expected_update_rate: 5.0
  # observation_persistance is necessary when clearing is
  # enabled. Otherwise, subsequent scans clear lower voxels too early.
  observation_persistence: 5.0
  marking: true
  # Clearing is necessary to set voxels to free if the laser scanner
  # clearly could see through it. This is particularly important for
  # points on the floor will not be cleared out by the tilt_laser
  # observation source since the floor appears in the raw scan.
  clearing: true
